# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'objmenu.ui'
#
# Created: Tue Jun 30 22:02:31 2009
#      by: PyQt4 UI code generator 4.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(197, 319)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 232, 232, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 232, 232, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 232, 232, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 232, 232, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        self.treeWidget = QtGui.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 191, 311))
        self.treeWidget.setObjectName("treeWidget")
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(item)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)
        item = QtGui.QTreeWidgetItem(self.treeWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setToolTip(QtGui.QApplication.translate("Form", "Drag and drop SndObj\'s to your workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("Form", "SndObj", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("Form", "ADSR", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("Form", "Balance", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("Form", "Buzz", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("Form", "Convol", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).setText(0, QtGui.QApplication.translate("Form", "DelayLine", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).child(0).setText(0, QtGui.QApplication.translate("Form", "Comb", None, QtGui.QApplication.UnicodeUTF8))
        '''
        self.treeWidget.topLevelItem(4).child(1).setText(0, QtGui.QApplication.translate("Form", "FIR", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).child(2).setText(0, QtGui.QApplication.translate("Form", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).child(3).setText(0, QtGui.QApplication.translate("Form", "SndLoop", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).child(4).setText(0, QtGui.QApplication.translate("Form", "StringFlt", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).child(4).child(0).setText(0, QtGui.QApplication.translate("Form", "Pluck", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).child(5).setText(0, QtGui.QApplication.translate("Form", "Tap", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).child(5).child(0).setText(0, QtGui.QApplication.translate("Form", "Tapi", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).child(6).setText(0, QtGui.QApplication.translate("Form", "VDelay", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(5).setText(0, QtGui.QApplication.translate("Form", "FastOsc", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(5).child(0).setText(0, QtGui.QApplication.translate("Form", "Osc", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(5).child(0).child(0).setText(0, QtGui.QApplication.translate("Form", "Osci", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(6).setText(0, QtGui.QApplication.translate("Form", "FFT", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(6).child(0).setText(0, QtGui.QApplication.translate("Form", "PVA", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(6).child(0).child(0).setText(0, QtGui.QApplication.translate("Form", "IFGram", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).setText(0, QtGui.QApplication.translate("Form", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(0).setText(0, QtGui.QApplication.translate("Form", "HiPass", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(1).setText(0, QtGui.QApplication.translate("Form", "LoPass", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(2).setText(0, QtGui.QApplication.translate("Form", "Lp", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(3).setText(0, QtGui.QApplication.translate("Form", "Reson", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(4).setText(0, QtGui.QApplication.translate("Form", "TpTz", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(4).child(0).setText(0, QtGui.QApplication.translate("Form", "Ap", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(4).child(1).setText(0, QtGui.QApplication.translate("Form", "ButtBP", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(4).child(1).child(0).setText(0, QtGui.QApplication.translate("Form", "ButtBR", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(4).child(1).child(1).setText(0, QtGui.QApplication.translate("Form", "ButtHP", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).child(4).child(1).child(2).setText(0, QtGui.QApplication.translate("Form", "ButtLP", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(8).setText(0, QtGui.QApplication.translate("Form", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(9).setText(0, QtGui.QApplication.translate("Form", "Hilb", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(10).setText(0, QtGui.QApplication.translate("Form", "IFFT", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(10).child(0).setText(0, QtGui.QApplication.translate("Form", "PVS", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(10).child(0).child(0).setText(0, QtGui.QApplication.translate("Form", "PVRead", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(11).setText(0, QtGui.QApplication.translate("Form", "Interp", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(12).setText(0, QtGui.QApplication.translate("Form", "Lookup", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(12).child(0).setText(0, QtGui.QApplication.translate("Form", "Lookupi", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(13).setText(0, QtGui.QApplication.translate("Form", "MidiIn", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(13).child(0).setText(0, QtGui.QApplication.translate("Form", "Bend", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(13).child(1).setText(0, QtGui.QApplication.translate("Form", "MidiMap", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(14).setText(0, QtGui.QApplication.translate("Form", "Mixer", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(15).setText(0, QtGui.QApplication.translate("Form", "Oscil", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(15).child(0).setText(0, QtGui.QApplication.translate("Form", "Oscili", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(15).child(0).child(0).setText(0, QtGui.QApplication.translate("Form", "PhOscili", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(15).child(1).setText(0, QtGui.QApplication.translate("Form", "Oscilt", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(16).setText(0, QtGui.QApplication.translate("Form", "Pan", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(17).setText(0, QtGui.QApplication.translate("Form", "Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(18).setText(0, QtGui.QApplication.translate("Form", "Rand", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(18).child(0).setText(0, QtGui.QApplication.translate("Form", "Randh", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(18).child(0).child(0).setText(0, QtGui.QApplication.translate("Form", "Randi", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(19).setText(0, QtGui.QApplication.translate("Form", "Ring", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(20).setText(0, QtGui.QApplication.translate("Form", "SinAnal", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(21).setText(0, QtGui.QApplication.translate("Form", "SinSyn", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(21).child(0).setText(0, QtGui.QApplication.translate("Form", "ResSyn", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(21).child(0).child(0).setText(0, QtGui.QApplication.translate("Form", "AdSyn", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(21).child(0).child(1).setText(0, QtGui.QApplication.translate("Form", "IFAdd", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(22).setText(0, QtGui.QApplication.translate("Form", "SndIn", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(23).setText(0, QtGui.QApplication.translate("Form", "SndRead", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(24).setText(0, QtGui.QApplication.translate("Form", "SpecIn", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(25).setText(0, QtGui.QApplication.translate("Form", "SpecMult", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(26).setText(0, QtGui.QApplication.translate("Form", "SyncGrain", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(27).setText(0, QtGui.QApplication.translate("Form", "Unit", None, QtGui.QApplication.UnicodeUTF8))
        '''
        self.treeWidget.setSortingEnabled(__sortingEnabled)

